apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-vhcf-net-tls
spec:
  dnsNames:
  - api.vhcf.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-vhcf-net-tls