apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
- discord/certificate.yaml
- discord/deployment.yaml
- discord/service.yaml
- discord/ingress.yaml
- frontend/certificate.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/ingress.yaml
- logging/logging.yaml
- chart-parser/cronjob.yaml
images:
- name: adhp/hcf-frontend
  newName: adhp/frontend
  newTag: hcf-v1.6.1677113706.18-9f6cdf9
- name: denartcc/api
  newName: adhp/api
  newTag: main-e9d09c0
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: df0fe4b
