apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- auth/certificate.yaml
- auth/deployment.yaml
- auth/ingress.yaml
- auth/service.yaml
images:
- name: denartcc/api
  newName: adhp/api
  newTag: main-0374a8d
- name: vzanartcc/auth
  newName: adhp/auth
  newTag: 72032a6
