apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: discord-vhcf-net-tls
spec:
  dnsNames:
  - discord.vhcf.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: discord-vhcf-net-tls