apiVersion: batch/v1
kind: CronJob
metadata:
  name: chart-parser
  namespace: hcf
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - envFrom:
            - secretRef:
                name: api-secrets
                optional: false
            env:
            - name: STATES
              value: "HI,XX"
            image: adhp/chart-parser:latest
            imagePullPolicy: Always
            name: chart-parser
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: 1 9 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
