apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-vhcf-net
spec:
  dnsNames:
  - auth.vhcf.net
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: tls-auth-vhcf-net
